# DEXI Default Configuration
# Copy this file to /home/dexi/.dexi-config.yaml to customize

nodes:
  yolo:
    enabled: false
    confidence_threshold: 0.5
  camera:
    enabled: true
    width: 640
    height: 480
    format: "XRGB8888"
    jpeg_quality: 60
  apriltag:
    enabled: false
    max_tags: 10
  gpio:
    enabled: true
  servo:
    enabled: true
  rosbridge:
    enabled: true

system:
  debug_mode: false
  log_level: "info"