# DEXI Default Configuration
# Copy this file to /home/dexi/.dexi-config.yaml to customize

nodes:
  apriltag:
    enabled: true
    max_tags: 10
  camera:
    enabled: true
    width: 320
    height: 240
    format: "XRGB8888"
    jpeg_quality: 75
  gpio:
    enabled: true
  offboard:
    enabled: false
    keyboard_control: false
  rosbridge:
    enabled: true
  servo:
    enabled: true
  yolo:
    enabled: true
    confidence_threshold: 0.5

system:
  debug_mode: false
  log_level: "info"